### ISSUE TITLE
As a developer, I want to program an HTCondor command map through the PGA portal so that the Airavata scheduler is able to call on HTCondor within resource nodes to natively submit a job.

### ISSUE THREAD

**Issue by docquantum** [unlhcc/rna-nanostructures-2021#11]
- [x] Get the PGA portal working
- [x] Map the HTCondor commands to the HTCondor submission
- [x] Test the HTCondor implementation using the PGA portal.

This will add support to creating HTCondor commands to enable running on the Open Science Grid.

**Comment by seamansJosh** [comment]
Looks Good
